name: My GitHub Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_v1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set User Information
      if: github.event_name == 'push'
      id: user_info_push
      run: |
        USER_NAME=$(git log -1 --pretty=format:'%an')
        COMMIT_TIME=$(git log -1 --pretty=format:'%ci')
        COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
        FROM_BRANCH=$(git symbolic-ref --short HEAD)  # Get the current branch name
        TO_BRANCH=${GITHUB_REF#refs/heads/}  # Remove the "refs/heads/" prefix from GITHUB_REF
        echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
        echo "COMMIT_TIME=$COMMIT_TIME" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "FROM_BRANCH=$FROM_BRANCH" >> $GITHUB_ENV
        echo "TO_BRANCH=$TO_BRANCH" >> $GITHUB_ENV
        
        if [ -f "profile.md" ]; then
          EXISTING_CONTEXT=$(cat profile.md)
        else
          EXISTING_CONTEXT=""
        fi
      
    - name: Run hjk-test-v1 action
      uses: hyeonjeong-ko/packiging-test@8.4
      with:
        test-variable: "친구에게 보내기!"
        send-to-function: "send_to_friends"
        refresh-token: "eu0pln4kk-tH3tCFuUrlK2GkMQBZCLLQZ1ZcibWBCiolUwAAAYoW42Zg" #나에게 보내기는 access-token이 필수
        msg-template: "feed"
        repo-url: "https://github.com/2020311920/presentation_test_1/new/test-branch"
        msg-img: "https://item.kakaocdn.net/do/416976b0c05bde28d706525b7c6c97ed41d1a2caccd0c566eab28b91e2e5d306"

        existing-context: $EXISTING_CONTEXT
        event_name: ${{ github.event_name }}
        MERGED_STATUS: ${{ github.event.pull_request.merged }}
        USER_NAME: $USER_NAME
        COMMIT_TIME: $COMMIT_TIME
        COMMIT_MESSAGE: $COMMIT_MESSAGE
        FROM_BRANCH: $FROM_BRANCH
        TO_BRANCH: $TO_BRANCH
